//go:build !ignore_autogenerated

// Copyright 2025 Upbound Inc.
// All rights reserved

// Code generated by controller-gen. DO NOT EDIT.

package upbound

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceExtension) DeepCopyInto(out *SpaceExtension) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(SpaceExtensionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceExtension.
func (in *SpaceExtension) DeepCopy() *SpaceExtension {
	if in == nil {
		return nil
	}
	out := new(SpaceExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpaceExtension) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceExtensionSpec) DeepCopyInto(out *SpaceExtensionSpec) {
	*out = *in
	if in.Disconnected != nil {
		in, out := &in.Disconnected, &out.Disconnected
		*out = new(DisconnectedConfiguration)
		**out = **in
	}
	if in.Cloud != nil {
		in, out := &in.Cloud, &out.Cloud
		*out = new(CloudConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceExtensionSpec.
func (in *SpaceExtensionSpec) DeepCopy() *SpaceExtensionSpec {
	if in == nil {
		return nil
	}
	out := new(SpaceExtensionSpec)
	in.DeepCopyInto(out)
	return out
}
