// Copyright 2025 Upbound Inc.
// All rights reserved

package common

import (
	"fmt"
	"reflect"

	"github.com/upbound/up/internal/version"
)

// ImageLabels returns the image labels that should be applied to images
// generated by the given command struct.
func ImageLabels(cmd any) map[string]string {
	return map[string]string{
		"io.upbound.up.userAgent": version.UserAgent(),
		"io.upbound.up.buildCmd":  getCmdOptions(cmd),
	}
}

// getCmdOptions generates a string of all command-line options from the command
// struct.
func getCmdOptions(cmd any) string {
	v := reflect.ValueOf(cmd)
	if v.Kind() == reflect.Pointer {
		v = v.Elem()
	}
	typeOfCmd := v.Type()

	var options string

	for i := range v.NumField() {
		field := typeOfCmd.Field(i)
		value := v.Field(i)
		if !value.CanInterface() {
			continue
		}
		if options != "" {
			options += ", "
		}
		options += fmt.Sprintf("%s: %v", field.Name, value.Interface())
	}

	return options
}
