//go:build !ignore_autogenerated

// Copyright 2025 Upbound Inc.
// All rights reserved

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/upbound/up-sdk-go/apis/spaces/v1beta1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2ETest) DeepCopyInto(out *E2ETest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2ETest.
func (in *E2ETest) DeepCopy() *E2ETest {
	if in == nil {
		return nil
	}
	out := new(E2ETest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *E2ETest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *E2ETestSpec) DeepCopyInto(out *E2ETestSpec) {
	*out = *in
	if in.Crossplane != nil {
		in, out := &in.Crossplane, &out.Crossplane
		*out = new(v1beta1.CrossplaneSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int)
		**out = **in
	}
	if in.SkipDelete != nil {
		in, out := &in.SkipDelete, &out.SkipDelete
		*out = new(bool)
		**out = **in
	}
	if in.DefaultConditions != nil {
		in, out := &in.DefaultConditions, &out.DefaultConditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraResources != nil {
		in, out := &in.ExtraResources, &out.ExtraResources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new E2ETestSpec.
func (in *E2ETestSpec) DeepCopy() *E2ETestSpec {
	if in == nil {
		return nil
	}
	out := new(E2ETestSpec)
	in.DeepCopyInto(out)
	return out
}
