//go:build !ignore_autogenerated

// Copyright 2025 Upbound Inc.
// All rights reserved

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositionTest) DeepCopyInto(out *CompositionTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositionTest.
func (in *CompositionTest) DeepCopy() *CompositionTest {
	if in == nil {
		return nil
	}
	out := new(CompositionTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CompositionTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositionTestSpec) DeepCopyInto(out *CompositionTestSpec) {
	*out = *in
	if in.Validate != nil {
		in, out := &in.Validate, &out.Validate
		*out = new(bool)
		**out = **in
	}
	in.XR.DeepCopyInto(&out.XR)
	in.XRD.DeepCopyInto(&out.XRD)
	in.Composition.DeepCopyInto(&out.Composition)
	if in.ObservedResources != nil {
		in, out := &in.ObservedResources, &out.ObservedResources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraResources != nil {
		in, out := &in.ExtraResources, &out.ExtraResources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AssertResources != nil {
		in, out := &in.AssertResources, &out.AssertResources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositionTestSpec.
func (in *CompositionTestSpec) DeepCopy() *CompositionTestSpec {
	if in == nil {
		return nil
	}
	out := new(CompositionTestSpec)
	in.DeepCopyInto(out)
	return out
}
