//go:build !ignore_autogenerated

// Copyright 2025 Upbound Inc.
// All rights reserved

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha1

import (
	"github.com/crossplane/crossplane/v2/apis/pkg/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDependencies) DeepCopyInto(out *APIDependencies) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(APIGitReference)
		**out = **in
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(APIHTTPReference)
		**out = **in
	}
	if in.K8s != nil {
		in, out := &in.K8s, &out.K8s
		*out = new(APIK8sReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDependencies.
func (in *APIDependencies) DeepCopy() *APIDependencies {
	if in == nil {
		return nil
	}
	out := new(APIDependencies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIGitReference) DeepCopyInto(out *APIGitReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGitReference.
func (in *APIGitReference) DeepCopy() *APIGitReference {
	if in == nil {
		return nil
	}
	out := new(APIGitReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIHTTPReference) DeepCopyInto(out *APIHTTPReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIHTTPReference.
func (in *APIHTTPReference) DeepCopy() *APIHTTPReference {
	if in == nil {
		return nil
	}
	out := new(APIHTTPReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIK8sReference) DeepCopyInto(out *APIK8sReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIK8sReference.
func (in *APIK8sReference) DeepCopy() *APIK8sReference {
	if in == nil {
		return nil
	}
	out := new(APIK8sReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
	if in.MatchImages != nil {
		in, out := &in.MatchImages, &out.MatchImages
		*out = make([]ImageMatch, len(*in))
		copy(*out, *in)
	}
	out.RewriteImage = in.RewriteImage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageMatch) DeepCopyInto(out *ImageMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageMatch.
func (in *ImageMatch) DeepCopy() *ImageMatch {
	if in == nil {
		return nil
	}
	out := new(ImageMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRewrite) DeepCopyInto(out *ImageRewrite) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRewrite.
func (in *ImageRewrite) DeepCopy() *ImageRewrite {
	if in == nil {
		return nil
	}
	out := new(ImageRewrite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(ProjectSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectPackageMetadata) DeepCopyInto(out *ProjectPackageMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectPackageMetadata.
func (in *ProjectPackageMetadata) DeepCopy() *ProjectPackageMetadata {
	if in == nil {
		return nil
	}
	out := new(ProjectPackageMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectPaths) DeepCopyInto(out *ProjectPaths) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectPaths.
func (in *ProjectPaths) DeepCopy() *ProjectPaths {
	if in == nil {
		return nil
	}
	out := new(ProjectPaths)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	out.ProjectPackageMetadata = in.ProjectPackageMetadata
	if in.Crossplane != nil {
		in, out := &in.Crossplane, &out.Crossplane
		*out = new(v1.CrossplaneConstraints)
		**out = **in
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]v1.Dependency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = new(ProjectPaths)
		**out = **in
	}
	if in.Architectures != nil {
		in, out := &in.Architectures, &out.Architectures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImageConfig != nil {
		in, out := &in.ImageConfig, &out.ImageConfig
		*out = make([]ImageConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.APIDependencies != nil {
		in, out := &in.APIDependencies, &out.APIDependencies
		*out = make([]APIDependencies, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}
