apiVersion: meta.dev.upbound.io/v1alpha1
kind: Project
metadata:
  name: e2e-test
spec:
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Upbound User <user@example.com>
  readme: |
    This is where you can add a readme for your project.
  repository: xpkg.upbound.io/upbound/e2e-test
  source: github.com/upbound/project-template
