// Copyright 2025 Upbound Inc.
// All rights reserved

package query

var (
	nativeKinds     = map[string]string{} //nolint: gochecknoglobals // we use it in tests
	nativeResources = map[string]string{  //nolint: gochecknoglobals // we use it in tests
		"PodDisruptionBudget":            "poddisruptionbudgets",
		"RoleBinding":                    "rolebindings",
		"Endpoints":                      "endpoints",
		"APIService":                     "apiservices",
		"Pod":                            "pods",
		"Event":                          "events",
		"ServiceAccount":                 "serviceaccounts",
		"FlowSchema":                     "flowschemas",
		"Node":                           "nodes",
		"PriorityLevelConfiguration":     "prioritylevelconfigurations",
		"Lease":                          "leases",
		"ValidatingWebhookConfiguration": "validatingwebhookconfigurations",
		"PriorityClass":                  "priorityclasses",
		"Namespace":                      "namespaces",
		"ConfigMap":                      "configmaps",
		"CustomResourceDefinition":       "customresourcedefinitions",
		"ClusterRoleBinding":             "clusterrolebindings",
		"Secret":                         "secrets",
		"Service":                        "services",
		"EndpointSlice":                  "endpointslices",
		"ReplicaSet":                     "replicasets",
		"Deployment":                     "deployments",
		"Role":                           "roles",
		"ClusterRole":                    "clusterroles",

		"Binding":                          "bindings",
		"CSIDriver":                        "csidrivers",
		"CSINode":                          "csinodes",
		"CSIStorageCapacity":               "csistoragecapacities",
		"CertificateSigningRequest":        "certificatesigningrequests",
		"ClusterTrustBundle":               "clustertrustbundles",
		"ComponentStatus":                  "componentstatuses",
		"ControllerRevision":               "controllerrevisions",
		"ConversionReview":                 "conversionreviews",
		"CronJob":                          "cronjobs",
		"DaemonSet":                        "daemonsets",
		"DeploymentRollback":               "deploymentrollbacks",
		"DeviceClass":                      "deviceclasses",
		"Eviction":                         "evictions",
		"HorizontalPodAutoscaler":          "horizontalpodautoscalers",
		"IPAddress":                        "ipaddresses",
		"Ingress":                          "ingresses",
		"IngressClass":                     "ingressclasses",
		"Job":                              "jobs",
		"LeaseCandidate":                   "leasecandidates",
		"LimitRange":                       "limitranges",
		"LocalSubjectAccessReview":         "localsubjectaccessreviews",
		"MutatingAdmissionPolicy":          "mutatingadmissionpolicies",
		"MutatingAdmissionPolicyBinding":   "mutatingadmissionpolicybindings",
		"MutatingWebhookConfiguration":     "mutatingwebhookconfigurations",
		"NetworkPolicy":                    "networkpolicies",
		"PersistentVolume":                 "persistentvolumes",
		"PersistentVolumeClaim":            "persistentvolumeclaims",
		"PodSchedulingContext":             "podscchedulingcontexts",
		"PodStatusResult":                  "podstatusresults",
		"PodTemplate":                      "podtemplates",
		"RangeAllocation":                  "rangeallocations",
		"ReplicationController":            "replicationcontrollers",
		"ResourceClaim":                    "resourceclaims",
		"ResourceClaimTemplate":            "resourceclaimtemplates",
		"ResourceClaimParameters":          "resourceclaimparameters",
		"ResourceClassParameters":          "resourceclassparameters",
		"ResourceSlice":                    "resourcesclices",
		"ResourceClass":                    "resourceclasses",
		"ResourceQuota":                    "resourcequotas",
		"RuntimeClass":                     "runtimeclasses",
		"SelfSubjectAccessReview":          "selfsubjectaccessreviews",
		"SelfSubjectReview":                "selfsubjectreviews",
		"SelfSubjectRulesReview":           "selfsubjectrulesreviews",
		"SerializedReference":              "serializedreferences",
		"ServiceCIDR":                      "servicecidrs",
		"StatefulSet":                      "statefulsets",
		"StorageClass":                     "storageclasses",
		"StorageVersion":                   "storageversions",
		"StorageVersionMigration":          "storageversionmigrations",
		"SubjectAccessReview":              "subjectaccessreviews",
		"TokenRequest":                     "tokenrequests",
		"TokenReview":                      "tokenreviews",
		"ValidatingAdmissionPolicy":        "validatingadmissionpolicies",
		"ValidatingAdmissionPolicyBinding": "validatingadmissionpolicybindings",
		"VolumeAttachment":                 "volumeattachments",
		"VolumeAttributesClass":            "volumeattributesclasses",
	}
)

func init() {
	for k, v := range nativeResources {
		nativeKinds[v] = k
	}
}
