//go:build !ignore_autogenerated

// Copyright 2025 Upbound Inc.
// All rights reserved

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationTest) DeepCopyInto(out *OperationTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationTest.
func (in *OperationTest) DeepCopy() *OperationTest {
	if in == nil {
		return nil
	}
	out := new(OperationTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperationTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationTestSpec) DeepCopyInto(out *OperationTestSpec) {
	*out = *in
	in.Operation.DeepCopyInto(&out.Operation)
	if in.RequiredResources != nil {
		in, out := &in.RequiredResources, &out.RequiredResources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AssertResources != nil {
		in, out := &in.AssertResources, &out.AssertResources
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationTestSpec.
func (in *OperationTestSpec) DeepCopy() *OperationTestSpec {
	if in == nil {
		return nil
	}
	out := new(OperationTestSpec)
	in.DeepCopyInto(out)
	return out
}
