// Copyright 2025 Upbound Inc.
// All rights reserved

package generator

import (
	"embed"
	"encoding/json"
	"testing"

	"github.com/invopop/jsonschema"
	"github.com/spf13/afero"
	"gotest.tools/v3/assert"
)

//go:embed testdata/*.json
var testdataJSONFS embed.FS

func TestGenerateFromCRD(t *testing.T) {
	inputFS := afero.NewBasePathFs(afero.FromIOFS{FS: testdataFS}, "testdata")
	schemaFS, err := jsonGenerator{}.GenerateFromCRD(t.Context(), inputFS, nil)
	assert.NilError(t, err)

	expectedFiles := []string{
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-DeleteOptions.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-FieldsV1.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-ListMeta.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-ManagedFieldsEntry.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-ObjectMeta.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-OwnerReference.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-Patch.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-Preconditions.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-StatusCause.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-StatusDetails.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-Status.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-Time.schema.json",
		"models/co-acme-platform-v1alpha1-AccountScaffold.schema.json",
		"models/co-acme-platform-v1alpha1-AccountScaffoldList.schema.json",
		"models/co-acme-platform-v1alpha1-XAccountScaffold.schema.json",
		"models/co-acme-platform-v1alpha1-XAccountScaffoldList.schema.json",
	}

	for _, path := range expectedFiles {
		exists, err := afero.Exists(schemaFS, path)
		assert.NilError(t, err)
		assert.Assert(t, exists, "expected model file %s does not exist", path)

		contents, err := afero.ReadFile(schemaFS, path)
		assert.NilError(t, err)

		var schema jsonschema.Schema
		err = json.Unmarshal(contents, &schema)
		assert.NilError(t, err)
	}
}

func TestGenerateFromOpenAPI(t *testing.T) {
	inputFS := afero.NewBasePathFs(afero.FromIOFS{FS: testdataJSONFS}, "testdata")
	schemaFS, err := jsonGenerator{}.GenerateFromOpenAPI(t.Context(), inputFS, nil)
	assert.NilError(t, err)

	expectedFiles := []string{
		"models/io-k8s-api-authentication-v1-BoundObjectReference.schema.json",
		"models/io-k8s-api-authentication-v1-TokenRequest.schema.json",
		"models/io-k8s-api-authentication-v1-TokenRequestSpec.schema.json",
		"models/io-k8s-api-authentication-v1-TokenRequestStatus.schema.json",
		"models/io-k8s-api-autoscaling-v1-Scale.schema.json",
		"models/io-k8s-api-autoscaling-v1-ScaleSpec.schema.json",
		"models/io-k8s-api-autoscaling-v1-ScaleStatus.schema.json",
		"models/io-k8s-api-core-v1-AWSElasticBlockStoreVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-Affinity.schema.json",
		"models/io-k8s-api-core-v1-AppArmorProfile.schema.json",
		"models/io-k8s-api-core-v1-AttachedVolume.schema.json",
		"models/io-k8s-api-core-v1-AzureDiskVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-AzureFilePersistentVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-AzureFileVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-Binding.schema.json",
		"models/io-k8s-api-core-v1-CSIPersistentVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-CSIVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-Capabilities.schema.json",
		"models/io-k8s-api-core-v1-CephFSPersistentVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-CephFSVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-CinderPersistentVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-CinderVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-ClientIPConfig.schema.json",
		"models/io-k8s-api-core-v1-ClusterTrustBundleProjection.schema.json",
		"models/io-k8s-api-core-v1-ComponentCondition.schema.json",
		"models/io-k8s-api-core-v1-ComponentStatus.schema.json",
		"models/io-k8s-api-core-v1-ComponentStatusList.schema.json",
		"models/io-k8s-api-core-v1-ConfigMap.schema.json",
		"models/io-k8s-api-core-v1-ConfigMapEnvSource.schema.json",
		"models/io-k8s-api-core-v1-ConfigMapKeySelector.schema.json",
		"models/io-k8s-api-core-v1-ConfigMapList.schema.json",
		"models/io-k8s-api-core-v1-ConfigMapNodeConfigSource.schema.json",
		"models/io-k8s-api-core-v1-ConfigMapProjection.schema.json",
		"models/io-k8s-api-core-v1-ConfigMapVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-Container.schema.json",
		"models/io-k8s-api-core-v1-ContainerImage.schema.json",
		"models/io-k8s-api-core-v1-ContainerPort.schema.json",
		"models/io-k8s-api-core-v1-ContainerResizePolicy.schema.json",
		"models/io-k8s-api-core-v1-ContainerState.schema.json",
		"models/io-k8s-api-core-v1-ContainerStateRunning.schema.json",
		"models/io-k8s-api-core-v1-ContainerStateTerminated.schema.json",
		"models/io-k8s-api-core-v1-ContainerStateWaiting.schema.json",
		"models/io-k8s-api-core-v1-ContainerStatus.schema.json",
		"models/io-k8s-api-core-v1-ContainerUser.schema.json",
		"models/io-k8s-api-core-v1-DaemonEndpoint.schema.json",
		"models/io-k8s-api-core-v1-DownwardAPIProjection.schema.json",
		"models/io-k8s-api-core-v1-DownwardAPIVolumeFile.schema.json",
		"models/io-k8s-api-core-v1-DownwardAPIVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-EmptyDirVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-EndpointAddress.schema.json",
		"models/io-k8s-api-core-v1-EndpointPort.schema.json",
		"models/io-k8s-api-core-v1-EndpointSubset.schema.json",
		"models/io-k8s-api-core-v1-Endpoints.schema.json",
		"models/io-k8s-api-core-v1-EndpointsList.schema.json",
		"models/io-k8s-api-core-v1-EnvFromSource.schema.json",
		"models/io-k8s-api-core-v1-EnvVar.schema.json",
		"models/io-k8s-api-core-v1-EnvVarSource.schema.json",
		"models/io-k8s-api-core-v1-EphemeralContainer.schema.json",
		"models/io-k8s-api-core-v1-EphemeralVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-Event.schema.json",
		"models/io-k8s-api-core-v1-EventList.schema.json",
		"models/io-k8s-api-core-v1-EventSeries.schema.json",
		"models/io-k8s-api-core-v1-EventSource.schema.json",
		"models/io-k8s-api-core-v1-ExecAction.schema.json",
		"models/io-k8s-api-core-v1-FCVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-FlexPersistentVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-FlexVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-FlockerVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-GCEPersistentDiskVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-GRPCAction.schema.json",
		"models/io-k8s-api-core-v1-GitRepoVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-GlusterfsPersistentVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-GlusterfsVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-HTTPGetAction.schema.json",
		"models/io-k8s-api-core-v1-HTTPHeader.schema.json",
		"models/io-k8s-api-core-v1-HostAlias.schema.json",
		"models/io-k8s-api-core-v1-HostIP.schema.json",
		"models/io-k8s-api-core-v1-HostPathVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-ISCSIPersistentVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-ISCSIVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-ImageVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-KeyToPath.schema.json",
		"models/io-k8s-api-core-v1-Lifecycle.schema.json",
		"models/io-k8s-api-core-v1-LifecycleHandler.schema.json",
		"models/io-k8s-api-core-v1-LimitRange.schema.json",
		"models/io-k8s-api-core-v1-LimitRangeItem.schema.json",
		"models/io-k8s-api-core-v1-LimitRangeList.schema.json",
		"models/io-k8s-api-core-v1-LimitRangeSpec.schema.json",
		"models/io-k8s-api-core-v1-LinuxContainerUser.schema.json",
		"models/io-k8s-api-core-v1-LoadBalancerIngress.schema.json",
		"models/io-k8s-api-core-v1-LoadBalancerStatus.schema.json",
		"models/io-k8s-api-core-v1-LocalObjectReference.schema.json",
		"models/io-k8s-api-core-v1-LocalVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-ModifyVolumeStatus.schema.json",
		"models/io-k8s-api-core-v1-NFSVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-Namespace.schema.json",
		"models/io-k8s-api-core-v1-NamespaceCondition.schema.json",
		"models/io-k8s-api-core-v1-NamespaceList.schema.json",
		"models/io-k8s-api-core-v1-NamespaceSpec.schema.json",
		"models/io-k8s-api-core-v1-NamespaceStatus.schema.json",
		"models/io-k8s-api-core-v1-Node.schema.json",
		"models/io-k8s-api-core-v1-NodeAddress.schema.json",
		"models/io-k8s-api-core-v1-NodeAffinity.schema.json",
		"models/io-k8s-api-core-v1-NodeCondition.schema.json",
		"models/io-k8s-api-core-v1-NodeConfigSource.schema.json",
		"models/io-k8s-api-core-v1-NodeConfigStatus.schema.json",
		"models/io-k8s-api-core-v1-NodeDaemonEndpoints.schema.json",
		"models/io-k8s-api-core-v1-NodeFeatures.schema.json",
		"models/io-k8s-api-core-v1-NodeList.schema.json",
		"models/io-k8s-api-core-v1-NodeRuntimeHandler.schema.json",
		"models/io-k8s-api-core-v1-NodeRuntimeHandlerFeatures.schema.json",
		"models/io-k8s-api-core-v1-NodeSelector.schema.json",
		"models/io-k8s-api-core-v1-NodeSelectorRequirement.schema.json",
		"models/io-k8s-api-core-v1-NodeSelectorTerm.schema.json",
		"models/io-k8s-api-core-v1-NodeSpec.schema.json",
		"models/io-k8s-api-core-v1-NodeStatus.schema.json",
		"models/io-k8s-api-core-v1-NodeSwapStatus.schema.json",
		"models/io-k8s-api-core-v1-NodeSystemInfo.schema.json",
		"models/io-k8s-api-core-v1-ObjectFieldSelector.schema.json",
		"models/io-k8s-api-core-v1-ObjectReference.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolume.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolumeClaim.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolumeClaimCondition.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolumeClaimList.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolumeClaimSpec.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolumeClaimStatus.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolumeClaimTemplate.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolumeClaimVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolumeList.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolumeSpec.schema.json",
		"models/io-k8s-api-core-v1-PersistentVolumeStatus.schema.json",
		"models/io-k8s-api-core-v1-PhotonPersistentDiskVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-Pod.schema.json",
		"models/io-k8s-api-core-v1-PodAffinity.schema.json",
		"models/io-k8s-api-core-v1-PodAffinityTerm.schema.json",
		"models/io-k8s-api-core-v1-PodAntiAffinity.schema.json",
		"models/io-k8s-api-core-v1-PodCondition.schema.json",
		"models/io-k8s-api-core-v1-PodDNSConfig.schema.json",
		"models/io-k8s-api-core-v1-PodDNSConfigOption.schema.json",
		"models/io-k8s-api-core-v1-PodIP.schema.json",
		"models/io-k8s-api-core-v1-PodList.schema.json",
		"models/io-k8s-api-core-v1-PodOS.schema.json",
		"models/io-k8s-api-core-v1-PodReadinessGate.schema.json",
		"models/io-k8s-api-core-v1-PodResourceClaim.schema.json",
		"models/io-k8s-api-core-v1-PodResourceClaimStatus.schema.json",
		"models/io-k8s-api-core-v1-PodSchedulingGate.schema.json",
		"models/io-k8s-api-core-v1-PodSecurityContext.schema.json",
		"models/io-k8s-api-core-v1-PodSpec.schema.json",
		"models/io-k8s-api-core-v1-PodStatus.schema.json",
		"models/io-k8s-api-core-v1-PodTemplate.schema.json",
		"models/io-k8s-api-core-v1-PodTemplateList.schema.json",
		"models/io-k8s-api-core-v1-PodTemplateSpec.schema.json",
		"models/io-k8s-api-core-v1-PortStatus.schema.json",
		"models/io-k8s-api-core-v1-PortworxVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-PreferredSchedulingTerm.schema.json",
		"models/io-k8s-api-core-v1-Probe.schema.json",
		"models/io-k8s-api-core-v1-ProjectedVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-QuobyteVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-RBDPersistentVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-RBDVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-ReplicationController.schema.json",
		"models/io-k8s-api-core-v1-ReplicationControllerCondition.schema.json",
		"models/io-k8s-api-core-v1-ReplicationControllerList.schema.json",
		"models/io-k8s-api-core-v1-ReplicationControllerSpec.schema.json",
		"models/io-k8s-api-core-v1-ReplicationControllerStatus.schema.json",
		"models/io-k8s-api-core-v1-ResourceClaim.schema.json",
		"models/io-k8s-api-core-v1-ResourceFieldSelector.schema.json",
		"models/io-k8s-api-core-v1-ResourceHealth.schema.json",
		"models/io-k8s-api-core-v1-ResourceQuota.schema.json",
		"models/io-k8s-api-core-v1-ResourceQuotaList.schema.json",
		"models/io-k8s-api-core-v1-ResourceQuotaSpec.schema.json",
		"models/io-k8s-api-core-v1-ResourceQuotaStatus.schema.json",
		"models/io-k8s-api-core-v1-ResourceRequirements.schema.json",
		"models/io-k8s-api-core-v1-ResourceStatus.schema.json",
		"models/io-k8s-api-core-v1-SELinuxOptions.schema.json",
		"models/io-k8s-api-core-v1-ScaleIOPersistentVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-ScaleIOVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-ScopeSelector.schema.json",
		"models/io-k8s-api-core-v1-ScopedResourceSelectorRequirement.schema.json",
		"models/io-k8s-api-core-v1-SeccompProfile.schema.json",
		"models/io-k8s-api-core-v1-Secret.schema.json",
		"models/io-k8s-api-core-v1-SecretEnvSource.schema.json",
		"models/io-k8s-api-core-v1-SecretKeySelector.schema.json",
		"models/io-k8s-api-core-v1-SecretList.schema.json",
		"models/io-k8s-api-core-v1-SecretProjection.schema.json",
		"models/io-k8s-api-core-v1-SecretReference.schema.json",
		"models/io-k8s-api-core-v1-SecretVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-SecurityContext.schema.json",
		"models/io-k8s-api-core-v1-Service.schema.json",
		"models/io-k8s-api-core-v1-ServiceAccount.schema.json",
		"models/io-k8s-api-core-v1-ServiceAccountList.schema.json",
		"models/io-k8s-api-core-v1-ServiceAccountTokenProjection.schema.json",
		"models/io-k8s-api-core-v1-ServiceList.schema.json",
		"models/io-k8s-api-core-v1-ServicePort.schema.json",
		"models/io-k8s-api-core-v1-ServiceSpec.schema.json",
		"models/io-k8s-api-core-v1-ServiceStatus.schema.json",
		"models/io-k8s-api-core-v1-SessionAffinityConfig.schema.json",
		"models/io-k8s-api-core-v1-SleepAction.schema.json",
		"models/io-k8s-api-core-v1-StorageOSPersistentVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-StorageOSVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-Sysctl.schema.json",
		"models/io-k8s-api-core-v1-TCPSocketAction.schema.json",
		"models/io-k8s-api-core-v1-Taint.schema.json",
		"models/io-k8s-api-core-v1-Toleration.schema.json",
		"models/io-k8s-api-core-v1-TopologySpreadConstraint.schema.json",
		"models/io-k8s-api-core-v1-TypedLocalObjectReference.schema.json",
		"models/io-k8s-api-core-v1-TypedObjectReference.schema.json",
		"models/io-k8s-api-core-v1-Volume.schema.json",
		"models/io-k8s-api-core-v1-VolumeDevice.schema.json",
		"models/io-k8s-api-core-v1-VolumeMount.schema.json",
		"models/io-k8s-api-core-v1-VolumeMountStatus.schema.json",
		"models/io-k8s-api-core-v1-VolumeNodeAffinity.schema.json",
		"models/io-k8s-api-core-v1-VolumeProjection.schema.json",
		"models/io-k8s-api-core-v1-VolumeResourceRequirements.schema.json",
		"models/io-k8s-api-core-v1-VsphereVirtualDiskVolumeSource.schema.json",
		"models/io-k8s-api-core-v1-WeightedPodAffinityTerm.schema.json",
		"models/io-k8s-api-core-v1-WindowsSecurityContextOptions.schema.json",
		"models/io-k8s-api-policy-v1-Eviction.schema.json",
		"models/io-k8s-apimachinery-pkg-api-resource-Quantity.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-APIResource.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-APIResourceList.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-APIVersions.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-Condition.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-DeleteOptions.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-FieldsV1.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-LabelSelector.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-LabelSelectorRequirement.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-ListMeta.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-ManagedFieldsEntry.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-MicroTime.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-ObjectMeta.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-OwnerReference.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-Patch.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-Preconditions.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-ServerAddressByClientCIDR.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-Status.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-StatusCause.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-StatusDetails.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-Time.schema.json",
		"models/io-k8s-apimachinery-pkg-apis-meta-v1-WatchEvent.schema.json",
		"models/io-k8s-apimachinery-pkg-runtime-RawExtension.schema.json",
		"models/io-k8s-apimachinery-pkg-util-intstr-IntOrString.schema.json",
	}

	for _, path := range expectedFiles {
		exists, err := afero.Exists(schemaFS, path)
		assert.NilError(t, err)
		assert.Assert(t, exists, "expected model file %s does not exist", path)

		contents, err := afero.ReadFile(schemaFS, path)
		assert.NilError(t, err)

		var schema jsonschema.Schema
		err = json.Unmarshal(contents, &schema)
		assert.NilError(t, err)
	}
}
