// Copyright 2025 Upbound Inc.
// All rights reserved

package run

import (
	"context"
	"embed"
	"maps"
	"net/url"
	"slices"
	"testing"

	"github.com/google/go-containerregistry/pkg/name"
	"github.com/spf13/afero"
	"gotest.tools/v3/assert"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"

	"github.com/upbound/up/internal/async"
	"github.com/upbound/up/internal/ctp"
	"github.com/upbound/up/internal/filesystem"
	"github.com/upbound/up/internal/project"
	"github.com/upbound/up/internal/upbound"
	"github.com/upbound/up/internal/upterm"
	"github.com/upbound/up/internal/xpkg/dep/resolver/image"
	"github.com/upbound/up/internal/xpkg/functions"
	"github.com/upbound/up/pkg/apis/project/v2alpha1"
)

var (
	//go:embed testdata/configuration-getting-started/**
	configurationGettingStarted embed.FS

	//go:embed testdata/packages/*
	packagesFS embed.FS
)

func TestRun(t *testing.T) {
	t.Parallel()

	// pusherTag is the tag that will be generated by the pusher.
	pusherTag, err := name.NewTag("example.com/test:latest")
	assert.NilError(t, err)
	// expectedTag is the tag that should be generated by the builder. We expect
	// it to be present in the image map that gets passed to the pusher or
	// sideloader.
	expectedTag, err := name.NewTag("xpkg.upbound.io/acmeco/configuration-getting-started:configuration")
	assert.NilError(t, err)

	tcs := map[string]struct {
		devCtp            ctp.DevControlPlane
		pusher            project.Pusher
		installFn         func(context.Context, client.Client, string, name.Tag, async.EventChannel) error
		extraResources    []runtime.RawExtension
		expectedResources []client.Object
	}{
		"Push": {
			devCtp: ctp.NewMockDevControlPlane(fake.NewClientBuilder().WithScheme(runtime.NewScheme()).Build(), nil),
			pusher: &mockPusher{
				tag:         pusherTag,
				expectedTag: expectedTag,
			},
			installFn: func(_ context.Context, _ client.Client, name string, tag name.Tag, _ async.EventChannel) error {
				if name != "configuration-getting-started" {
					return errors.Errorf("wrong configuration name: expected %q got %q", "configuration-getting-started", name)
				}
				// When using a pusher, we should install the tag that was
				// generated by the pusher.
				if tag.String() != pusherTag.String() {
					return errors.Errorf("wrong tag: expected %q got %q", pusherTag, tag)
				}
				return nil
			},
		},
		"ExtraResources": {
			devCtp: ctp.NewMockDevControlPlane(fake.NewClientBuilder().WithScheme(runtime.NewScheme()).Build(), nil),
			pusher: &mockPusher{
				tag:         pusherTag,
				expectedTag: expectedTag,
			},
			installFn: func(_ context.Context, _ client.Client, name string, tag name.Tag, _ async.EventChannel) error {
				if name != "configuration-getting-started" {
					return errors.Errorf("wrong configuration name: expected %q got %q", "configuration-getting-started", name)
				}
				if tag.String() != pusherTag.String() {
					return errors.Errorf("wrong tag: expected %q got %q", pusherTag, tag)
				}
				return nil
			},
			extraResources: []runtime.RawExtension{{
				Raw: []byte(`{"apiVersion":"v1","kind":"ConfigMap","metadata":{"name":"test-configmap","namespace":"default"},"data":{"key":"value"}}`),
			}},
			expectedResources: []client.Object{
				&corev1.ConfigMap{
					TypeMeta: v1.TypeMeta{
						APIVersion: "v1",
						Kind:       "ConfigMap",
					},
					ObjectMeta: v1.ObjectMeta{
						Name:      "test-configmap",
						Namespace: "default",
					},
					Data: map[string]string{
						"key": "value",
					},
				},
			},
		},
		"Sideload": {
			devCtp: &ctp.MockSideloadingDevControlPlane{
				MockDevControlPlane: *ctp.NewMockDevControlPlane(fake.NewClientBuilder().WithScheme(runtime.NewScheme()).Build(), nil),
				SideloadFn: func(_ context.Context, _ project.ImageTagMap, tag name.Tag) error {
					wantRepo, gotRepo := expectedTag.Context().Name(), tag.Context().Name()
					if wantRepo != gotRepo {
						return errors.Errorf("wrong repository in sideload: expected %q got %q", wantRepo, gotRepo)
					}
					return nil
				},
			},
			// No push should happen.
			pusher: nil,
			installFn: func(_ context.Context, _ client.Client, name string, tag name.Tag, _ async.EventChannel) error {
				if name != "configuration-getting-started" {
					return errors.Errorf("wrong configuration name: expected %q got %q", "configuration-getting-started", name)
				}
				// When we sideload, we install using the original repository
				// and a generated tag.
				wantRepo, gotRepo := expectedTag.Context().Name(), tag.Context().Name()
				if wantRepo != gotRepo {
					return errors.Errorf("wrong repository in install: expected %q got %q", wantRepo, gotRepo)
				}
				return nil
			},
		},
	}

	for testName, tc := range tcs {
		t.Run(testName, func(t *testing.T) {
			t.Parallel()

			projFS := filesystem.MemOverlay(
				afero.NewBasePathFs(
					afero.FromIOFS{FS: configurationGettingStarted},
					"testdata/configuration-getting-started",
				),
			)

			testPkgFS := afero.NewBasePathFs(afero.FromIOFS{FS: packagesFS}, "testdata/packages")

			prj, err := project.ParseWithVersion(projFS, "upbound.yaml")
			assert.NilError(t, err)
			prj.Default()

			ep, err := url.Parse("https://donotuse.example.com")
			assert.NilError(t, err)
			upCtx := &upbound.Context{
				Domain:           &url.URL{},
				RegistryEndpoint: ep,
			}
			mgr, err := project.NewDependencyManager(upCtx, prj.Project, projFS,
				project.WithCacheFS(afero.NewMemMapFs()),
				project.WithFetcher(&image.FSFetcher{FS: testPkgFS}),
				project.WithSchemaGenerators(nil),
			)
			assert.NilError(t, err)

			printer := upterm.DefaultObjPrinter
			printer.Quiet = true
			c := &Cmd{
				Flags: Flags{
					ProjectFile:  "upbound.yaml",
					NoBuildCache: true,
				},
				NoUpdateKubeconfig: true,
				Local:              true,

				projFS:             projFS,
				functionIdentifier: functions.FakeIdentifier,
				concurrency:        1,
				asyncWrapper:       async.IgnoreEvents,
				pusher:             tc.pusher,
				extraResources:     tc.extraResources,
				ensureDevControlPlane: func(_ context.Context, _ *upbound.Context, _ ...ctp.EnsureDevControlPlaneOption) (ctp.DevControlPlane, error) {
					return tc.devCtp, nil
				},
				installConfiguration: tc.installFn,

				m:       mgr,
				proj:    prj,
				printer: printer,
			}

			err = c.Run(t.Context(), upCtx)
			assert.NilError(t, err)

			// Check that any extra resources were created.
			cl := tc.devCtp.Client()
			for _, res := range tc.expectedResources {
				var u unstructured.Unstructured
				u.SetGroupVersionKind(res.GetObjectKind().GroupVersionKind())
				err := cl.Get(t.Context(), client.ObjectKeyFromObject(res), &u)
				assert.NilError(t, err)
			}
		})
	}
}

type mockPusher struct {
	expectedTag name.Tag
	tag         name.Tag
}

func (m mockPusher) Push(_ context.Context, _ *v2alpha1.Project, imgMap project.ImageTagMap, _ ...project.PushOption) (name.Tag, error) {
	if _, ok := imgMap[m.expectedTag]; !ok {
		gotKeys := slices.Collect(maps.Keys(imgMap))
		return name.Tag{}, errors.Errorf("did not find image %q to push, got %v", m.expectedTag.String(), gotKeys)
	}

	return m.tag, nil
}
