# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_call:
    secrets:
      upbound-bot-github-token:
        description: 'GitHub token for private module access'
        required: true

jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2404
    steps:
      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.upbound-bot-github-token }}:x-oauth-basic@github.com/upbound".insteadOf "https://github.com/upbound"

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Setup Go
        id: setup-go
        uses: useblacksmith/setup-go@647ac649bd5b480f2a262e3e3e5f4d150ed452ad # v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Mount Go build cache
        uses: useblacksmith/stickydisk@a652394bf1bf95399f406e648482b41fbd25c51f # v1
        with:
          key: ${{ github.repository }}-go-cache
          path: ~/.cache/go-build

      - name: Mount Go mod cache
        uses: useblacksmith/stickydisk@a652394bf1bf95399f406e648482b41fbd25c51f # v1
        with:
          key: ${{ github.repository }}-go-mod-cache
          path: ~/go/pkg/mod

      - name: Build
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          args: build --snapshot

      - name: Upload Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: output
          path: |
            _output/up_linux_amd64_v1/up
            _output/up_windows_amd64_v1/up.exe
          if-no-files-found: error
