# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Promote

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to promote (e.g. v0.1.0); defaults to `git describe`'
        required: false
        type: string
        default: ''
      channel:
        description: 'Release channel'
        required: true
        type: string
    secrets:
      xpkg-access-id:
        description: 'XPKG registry access ID'
        required: false
      xpkg-token:
        description: 'XPKG registry token'
        required: false
      aws-usr:
        description: 'AWS access key ID'
        required: false
      aws-psw:
        description: 'AWS secret access key'
        required: false

jobs:
  promote-artifacts:
    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
      - name: Install crane
        uses: imjasonh/setup-crane@v0.1

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Login to Upbound
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.xpkg-access-id }}
          password: ${{ secrets.xpkg-token }}

      - name: Promote Artifacts in S3 and xpkg
        run: hack/promote.sh
        env:
          VERSION: ${{ inputs.version }}
          CHANNEL: ${{ inputs.channel }}
          S3_BUCKET: public-cli.releases
          OCI_REPOSITORY: xpkg.upbound.io/upbound/up-cli
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-usr }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-psw }}
          AWS_DEFAULT_REGION: us-west-2
