name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    permissions:
      pull-requests: write
    if: github.actor == 'upbound-self-hosted-renovate[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4