# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  pull_request: {}
  merge_group:
    types: [checks_requested]

permissions:
  id-token: write   # Required for OIDC authentication
  contents: write   # Required for release creation

jobs:
  check:
    uses: ./.github/workflows/_check.yml
    with:
      golangci-version: 'v2.6.2'
    secrets:
      upbound-bot-github-token: ${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}

  build:
    uses: ./.github/workflows/_build.yml
    secrets:
      upbound-bot-github-token: ${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}

  e2e-tests:
    uses: ./.github/workflows/_e2e.yml
    needs: [build, check]
    with:
      aws-region: us-east-1
    secrets:
      upbound-robot-token: ${{ secrets.UPBOUND_ROBOT_TOKEN }}
      upbound-robot-id: ${{ secrets.UPBOUND_ROBOT_ID }}
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN_E2E_TEST }}
      upbound-bot-github-token: ${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}
