name: CI

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - 'v*'
  pull_request: {}
  workflow_dispatch: {}
  merge_group:
    types: [checks_requested]

env:
  # Common versions
  GOLANGCI_VERSION: 'v1.64.8'
  DOCKER_BUILDX_VERSION: 'v0.17.1'
  REGISTRY_ORGS: xpkg.upbound.io/upbound

  # Common users. We can't run a step 'if secrets.AWS_USR != ""' but we can run
  # a step 'if env.AWS_USR' != ""', so we copy these to succinctly test whether
  # credentials have been provided before trying to run steps that need them.
  DOCKER_USR: ${{ secrets.DOCKER_USR }}
  AWS_USR: ${{ secrets.AWS_USR }}
  XPKG_ACCESS_ID: ${{ secrets.XPKG_ACCESS_ID }}

jobs:
  detect-noop:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'

  lint:
    runs-on: blacksmith-8vcpu-ubuntu-2404-arm
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}:x-oauth-basic@github.com/upbound".insteadOf "https://github.com/upbound"

      - name: Setup Go
        id: setup-go
        uses: useblacksmith/setup-go@647ac649bd5b480f2a262e3e3e5f4d150ed452ad # v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Set Go cache date
        shell: bash
        run: echo "GO_CACHE_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      # NOTE: We restore the cache in all jobs that use Go, but save the cache
      # only from publish-artifacts. This is because publish-artifacts is the
      # only job whose cache contains build objects for all platforms.
      - name: Restore Go cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}-${{ env.GO_CACHE_DATE }}
          restore-keys: |
            go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}-
            go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-
            go-${{ runner.os }}-

      # We could run 'make lint' to ensure our desired Go version, but we prefer
      # this action because it leaves 'annotations' (i.e. it comments on PRs to
      # point out linter violations).
      - name: Lint
        uses: useblacksmith/golangci-lint-action@a441b42f4a441117ad7ee20b8d84a061db747efe # v6
        with:
          version: ${{ env.GOLANGCI_VERSION }}
          skip-go-installation: true
          only-new-issues: true

  check-diff:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}:x-oauth-basic@github.com/upbound".insteadOf "https://github.com/upbound"

      - name: Setup Go
        id: setup-go
        uses: useblacksmith/setup-go@647ac649bd5b480f2a262e3e3e5f4d150ed452ad # v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Set Go cache date
        shell: bash
        run: echo "GO_CACHE_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      # NOTE: We restore the cache in all jobs that use Go, but save the cache
      # only from publish-artifacts. This is because publish-artifacts is the
      # only job whose cache contains build objects for all platforms.
      - name: Restore Go cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}-${{ env.GO_CACHE_DATE }}
          restore-keys: |
            go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}-
            go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-
            go-${{ runner.os }}-

      - name: Check Diff
        run: make check-diff

  unit-tests:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}:x-oauth-basic@github.com/upbound".insteadOf "https://github.com/upbound"

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Setup Go
        id: setup-go
        uses: useblacksmith/setup-go@647ac649bd5b480f2a262e3e3e5f4d150ed452ad # v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Set Go cache date
        shell: bash
        run: echo "GO_CACHE_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      # NOTE: We restore the cache in all jobs that use Go, but save the cache
      # only from publish-artifacts. This is because publish-artifacts is the
      # only job whose cache contains build objects for all platforms.
      - name: Restore Go cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}-${{ env.GO_CACHE_DATE }}
          restore-keys: |
            go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}-
            go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-
            go-${{ runner.os }}-

      - name: Run Unit Tests
        run: |
          GO_TAGS="integration" make -j2 test

  publish-artifacts:
    runs-on: blacksmith-8vcpu-ubuntu-2404-arm
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}:x-oauth-basic@github.com/upbound".insteadOf "https://github.com/upbound"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          install: true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Setup Go
        id: setup-go
        uses: useblacksmith/setup-go@647ac649bd5b480f2a262e3e3e5f4d150ed452ad # v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Set Go cache date
        shell: bash
        run: echo "GO_CACHE_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      # NOTE: We restore the cache in all jobs that use Go, but save the cache
      # only from publish-artifacts. This is because publish-artifacts is the
      # only job whose cache contains build objects for all platforms.
      - name: Restore Go cache
        id: restore-cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}-${{ env.GO_CACHE_DATE }}
          restore-keys: |
            go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}-
            go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-
            go-${{ runner.os }}-

      - name: Build Artifacts
        run: make -j2 build.all
        env:
          # We're using docker buildx, which doesn't actually load the images it
          # builds by default. Specifying --load does so.
          BUILD_ARGS: "--load"
          RELEASE_TARGET: "release"

      - name: Save Go cache
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        if: steps.restore-cache.outputs.cache-hit != 'true'
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ runner.os }}-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}-${{ env.GO_CACHE_DATE }}

      - name: Publish Artifacts to GitHub
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: output
          path: _output/**

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux AMD64 schema-generator
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_output/bin/linux_amd64/schema-generator
          asset_name: schema-generator-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Linux ARM64 schema-generator
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_output/bin/linux_arm64/schema-generator
          asset_name: schema-generator-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload Darwin AMD64 schema-generator
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_output/bin/darwin_amd64/schema-generator
          asset_name: schema-generator-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Darwin ARM64 schema-generator
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_output/bin/darwin_arm64/schema-generator
          asset_name: schema-generator-darwin-arm64
          asset_content_type: application/octet-stream

      - name: Upload Linux AMD64 up
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_output/bin/linux_amd64/up
          asset_name: up-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Linux ARM64 up
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_output/bin/linux_arm64/up
          asset_name: up-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload Darwin AMD64 up
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_output/bin/darwin_amd64/up
          asset_name: up-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Darwin ARM64 up
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_output/bin/darwin_arm64/up
          asset_name: up-darwin-arm64
          asset_content_type: application/octet-stream

      - name: Login to Docker
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        if: env.DOCKER_USR != ''
        with:
          username: ${{ secrets.DOCKER_USR }}
          password: ${{ secrets.DOCKER_PSW }}

      - name: Login to Upbound
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        if: env.XPKG_ACCESS_ID != ''
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.XPKG_ACCESS_ID }}
          password: ${{ secrets.XPKG_TOKEN }}

      - name: Publish Artifacts to S3 and Docker Hub
        run: make -j2 publish BRANCH_NAME=${GITHUB_REF##*/}
        if: env.AWS_USR != '' && env.DOCKER_USR != ''
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_USR }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PSW }}
          AWS_DEFAULT_REGION: us-east-1
          GIT_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote Artifacts in S3 and Docker Hub
        if: github.ref == 'refs/heads/main' && env.AWS_USR != '' && env.DOCKER_USR != ''
        run: make -j2 promote
        env:
          BRANCH_NAME: main
          CHANNEL: main
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_USR }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PSW }}
          AWS_DEFAULT_REGION: us-east-1

  e2e:
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    needs: publish-artifacts
    if: needs.detect-noop.outputs.noop != 'true'

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: output
          path: _output

      - name: Platform Architecture
        id: determine-platform
        run: |
          PLATFORM=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          case "$ARCH" in
            x86_64) ARCH="amd64" ;;
            aarch64) ARCH="arm64" ;;
            *) echo "Unsupported architecture: $ARCH" && exit 1 ;;
          esac
          PLATFORM_ARCH="${PLATFORM}_${ARCH}"
          echo "PLATFORM_ARCH=${PLATFORM_ARCH}" >> $GITHUB_ENV

      - name: up
        run: |
          mkdir -p ~/up-cli-bin
          cp _output/bin/${{ env.PLATFORM_ARCH }}/up ~/up-cli-bin/
          chmod +x ~/up-cli-bin/up
          echo "$HOME/up-cli-bin" >> $GITHUB_PATH

      - name: up version
        run: |
          up version

      # TODO(adamwg): Change back to upbound once UXPv2 is public.
      - name: up login with robot
        run: |
          up login -t ${{ secrets.UPBOUND_DEV_TOKEN }} --organization=upbound-dev

      - name: up project init
        run: |
          up project init --empty e2e-test

      - name: assert project
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: cat e2e-test/upbound.yaml
          assert_file_path: e2e/project.yaml
          expected_result: PASSED

      - name: up project deps
        run: |
          cd e2e-test
          up dep add xpkg.upbound.io/upbound/provider-kubernetes

      - name: assert project with deps
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: cat e2e-test/upbound.yaml
          assert_file_path: e2e/project-with-dependencies.yaml
          expected_result: PASSED

      - name: up example generate
        run: |
          cd e2e-test
          up example generate \
            --type xr \
            --api-group acme.comp \
            --api-version v1beta1 \
            --kind XCluster \
            --name example

      - name: assert claim
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: cat e2e-test/examples/xcluster/example.yaml
          assert_file_path: e2e/example.yaml
          expected_result: PASSED

      - name: up xrd generate
        run: |
          cd e2e-test
          up xrd generate examples/xcluster/example.yaml

      - name: assert xrd
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: cat e2e-test/apis/xclusters/definition.yaml
          assert_file_path: e2e/definition.yaml
          expected_result: PASSED

      - name: up composition generate
        run: |
          cd e2e-test
          up composition generate examples/xcluster/example.yaml

      - name: assert composition
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: cat e2e-test/apis/xclusters/composition.yaml
          assert_file_path: e2e/composition.yaml
          expected_result: PASSED

      - name: assert project after composition generate
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: cat e2e-test/upbound.yaml
          assert_file_path: e2e/project-after-compositon-generate.yaml
          expected_result: PASSED

      - name: up function generate
        run: |
          cd e2e-test
          up function generate xcluster apis/xclusters/composition.yaml

      - name: assert composition with embedded function
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: cat e2e-test/apis/xclusters/composition.yaml
          assert_file_path: e2e/composition-with-embedded-function.yaml
          expected_result: PASSED

      - name: assert main.k from embedded function
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: cat e2e-test/functions/xcluster/main.k
          assert_file_path: e2e/main.k
          expected_result: PASSED

      - name: up project build
        run: |
          cd e2e-test
          up project build

      - name: assert uppkg exists
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: ls _output/e2e-test.uppkg
          contains: _output/e2e-test.uppkg
          expected_result: PASSED

      # TODO(adamwg): Change back to upbound once UXPv2 is public.
      - name: Login to xpkg with robot
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.UPBOUND_DEV_USERNAME }}
          password: ${{ secrets.UPBOUND_DEV_TOKEN }}

      # TODO(adamwg): Re-enable once UXPv2 is public.
      # - name: up project push
      #   run: |
      #     eval $(make --no-print-directory build.vars)
      #     cd e2e-test
      #     up project push --tag=${VERSION}

      - name: up project run
        run: |
          eval $(make --no-print-directory build.vars)
          cd e2e-test
          up project run --local --timeout=30m
          # The run command waits for packages to be healthy; make sure that's
          # working properly by waiting a very short interval for health.
          kubectl wait configurations.pkg --all --for=condition=Installed --timeout 5s
          kubectl wait pkg --all --for=condition=Healthy --timeout 5s
          kubectl wait pkgrev --all --for=condition=RevisionHealthy --timeout 5s
          kubectl wait providerrevision --all --for=condition=RuntimeHealthy --timeout 5s
          kubectl wait functionrevision --all --for=condition=RuntimeHealthy --timeout 5s

      - name: up project stop
        run: |
          cd e2e-test
          up project stop --local --force

      - name: assert kind cluster was destroyed
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: kind get clusters
          contains: e2e-test
          expected_result: FAILED

      - name: assert docker container were removed
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: docker ps -a
          contains: e2e-test
          expected_result: FAILED

  e2e-project-example-aws:
    runs-on: blacksmith
    needs: publish-artifacts
    if: needs.detect-noop.outputs.noop != 'true'

    strategy:
      matrix:
        language: [go, go-templating, kcl, python]
        test-language: [kcl, python]

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      # We need go to build the project, since it contains go functions. No need
      # for the go cache here, since we're only building embedded functions, not
      # up itself.
      - name: Setup Go
        id: setup-go
        uses: useblacksmith/setup-go@647ac649bd5b480f2a262e3e3e5f4d150ed452ad # v6
        with:
          go-version-file: go.mod
          cache: false

      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: output
          path: _output

      - name: Platform Architecture
        id: determine-platform
        run: |
          PLATFORM=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          case "$ARCH" in
            x86_64) ARCH="amd64" ;;
            aarch64) ARCH="arm64" ;;
            *) echo "Unsupported architecture: $ARCH" && exit 1 ;;
          esac
          PLATFORM_ARCH="${PLATFORM}_${ARCH}"
          echo "PLATFORM_ARCH=${PLATFORM_ARCH}" >> $GITHUB_ENV

      - name: up
        run: |
          mkdir -p ~/up-cli-bin
          cp _output/bin/${{ env.PLATFORM_ARCH }}/up ~/up-cli-bin/
          chmod +x ~/up-cli-bin/up
          echo "$HOME/up-cli-bin" >> $GITHUB_PATH

      - name: up version
        run: |
          up version

      - name: up project init project-example-aws
        run: |
          up project init --organization=upbound -e upbound/project-example-aws --language ${{ matrix.language }} --test-language ${{ matrix.test-language }} project-example-aws
          cd project-example-aws
          up project build

      - name: up composition render project-example-aws
        run: |
          cd project-example-aws
          up composition render apis/xstoragebucket/composition.yaml examples/xstoragebuckets/example.yaml --xrd apis/xstoragebucket/definition.yaml -q >> render.yaml

      - name: assert up composition render
        uses: GuillaumeFalourd/assert-command-line-output@main
        with:
          command_line: cat project-example-aws/render.yaml
          assert_file_path: e2e/render-${{ matrix.language }}.yaml
          expected_result: PASSED

      - name: up test run example-project-aws
        if: matrix.test-language == 'kcl' || matrix.test-language == 'python'
        run: |
          cd project-example-aws
          up test run tests/*

      - name: up login with robot
        run: |
          up login -t ${{ secrets.UPBOUND_ROBOT_TOKEN }} --organization=upbound

      - name: up ctx
        run: |
          up ctx upbound/upbound-gcp-us-central-1/default

      - name: Login to xpkg with robot
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.UPBOUND_ROBOT_ID }}
          password: ${{ secrets.UPBOUND_ROBOT_TOKEN }}

      - name: up test run --e2e example-project-aws
        # Only run e2e tests for kcl and python, since the other languages don't have e2e tests.
        if: (matrix.language == 'kcl' && matrix.test-language == 'kcl') || (matrix.language == 'python' && matrix.test-language == 'python')
        run: |
          cd project-example-aws
          up test run tests/e2etest-xstoragebucket --e2e
