name: Labels

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 0 * * *'

jobs:
  create-labels:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create Default Labels
        uses: crazy-max/ghaction-github-labeler@f8d36db286402ecb67054c6a14ec17ba2cd681a0 # v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/default-labels.yml
          skip-delete: true
