name: Labels

on:
  workflow_dispatch: {}
  schedule:
    - cron:  '0 0 * * *'

jobs:
  create-labels:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create Default Labels
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/default-labels.yml
          skip-delete: true
