# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      channel:
        description: 'Release channel'
        required: true
        default: 'alpha'

jobs:
  promote-artifacts:
    uses: ./.github/workflows/_promote.yml
    with:
      version: ${{ inputs.version }}
      channel: ${{ inputs.channel }}
    secrets:
      xpkg-access-id: ${{ secrets.XPKG_ACCESS_ID }}
      xpkg-token: ${{ secrets.XPKG_TOKEN }}
      aws-usr: ${{ secrets.AWS_USR }}
      aws-psw: ${{ secrets.AWS_PSW }}
