# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      channel:
        description: 'Release channel'
        required: true
        type: choice
        options:
          - alpha
          - stable
        default: alpha

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

jobs:
  promote-artifacts:
    uses: ./.github/workflows/_promote.yml
    with:
      version: ${{ inputs.version }}
      channel: ${{ inputs.channel }}
    secrets:
      xpkg-access-id: ${{ secrets.XPKG_ACCESS_ID }}
      xpkg-token: ${{ secrets.XPKG_TOKEN }}
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN_ARTIFACT_PUBLISH }}
