# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v0.1.0)'
        required: true
        type: string

permissions:
  id-token: write   # Required for OIDC authentication
  contents: write   # Required for release creation

jobs:
  validate-version:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: blacksmith-8vcpu-ubuntu-2404
    steps:
      - name: Validate semver
        uses: matt-usurp/validate-semver@7bbc9584679de1aeef57aa531504ab00438481ab # v2.1.0
        with:
          version: ${{ github.event.inputs.version }}

  check:
    needs: [validate-version]
    uses: ./.github/workflows/_check.yml
    with:
      golangci-version: 'v2.6.2'
    secrets:
      upbound-bot-github-token: ${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}

  release:
    needs: [validate-version]
    uses: ./.github/workflows/_release.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      xpkg-access-id: ${{ secrets.XPKG_ACCESS_ID }}
      xpkg-token: ${{ secrets.XPKG_TOKEN }}
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN_ARTIFACT_PUBLISH }}
      upbound-bot-github-token: ${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}

  e2e-tests:
    uses: ./.github/workflows/_e2e.yml
    needs: [release, check]
    with:
      aws-region: us-east-1
    secrets:
      upbound-robot-token: ${{ secrets.UPBOUND_ROBOT_TOKEN }}
      upbound-robot-id: ${{ secrets.UPBOUND_ROBOT_ID }}
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN_E2E_TEST }}
