# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release

on:
  push:
    # We run the release workflow on pushes to main and release branches so that
    # we get builds in S3 for every merge.
    branches:
      - main
      - release-*
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v0.1.0)'
        required: true
        type: string

permissions:
  id-token: write   # Required for OIDC authentication
  contents: write   # Required for release creation

jobs:
  check:
    uses: ./.github/workflows/_check.yml
    with:
      golangci-version: 'v1.64.8'
    secrets:
      upbound-bot-github-token: ${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}

  release:
    uses: ./.github/workflows/_release.yml
    with:
      version: ${{ github.event.inputs.version || '' }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      xpkg-access-id: ${{ secrets.XPKG_ACCESS_ID }}
      xpkg-token: ${{ secrets.XPKG_TOKEN }}
      aws-usr: ${{ secrets.AWS_USR }}
      aws-psw: ${{ secrets.AWS_PSW }}
      upbound-bot-github-token: ${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}

  e2e-tests:
    uses: ./.github/workflows/_e2e.yml
    needs: [release, check]
    with:
      aws-region: us-east-1
    secrets:
      upbound-robot-token: ${{ secrets.UPBOUND_ROBOT_TOKEN }}
      upbound-robot-id: ${{ secrets.UPBOUND_ROBOT_ID }}
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

  promote-main:
    if: ${{ github.event_name == "push" && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/_promote.yml
    needs: [release, e2e-tests]
    with:
      channel: main
      version: ${{ needs.release.outputs.version }}
    secrets:
      xpkg-access-id: ${{ secrets.XPKG_ACCESS_ID }}
      xpkg-token: ${{ secrets.XPKG_TOKEN }}
      aws-usr: ${{ secrets.AWS_USR }}
      aws-psw: ${{ secrets.AWS_PSW }}
