name: Renovate
on:
  # Allows manual/automated trigger for debugging purposes
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Renovate's log level"
        required: true
        default: "info"
        type: string
  schedule:
    - cron: '0 8 * * *'

env:
  LOG_LEVEL: "info"

jobs:
  renovate:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    if: |
      !github.event.repository.fork &&
      !github.event.pull_request.head.repo.fork
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      # Don't waste time starting Renovate if JSON is invalid
      - name: Validate Renovate JSON
        run:  npx --yes --package renovate -- renovate-config-validator

      - name: Get token
        id: get-github-app-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
        with:
          app-id: ${{ secrets.RENOVATE_GITHUB_APP_ID }}
          private-key: ${{ secrets.RENOVATE_GITHUB_APP_PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@8ac70de2fe55752c573155866e30735411e3b61c # v41.0.22
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # Use GitHub API to create commits
          RENOVATE_PLATFORM_COMMIT: "true"
          LOG_LEVEL: ${{ github.event.inputs.logLevel || env.LOG_LEVEL }}
          # Our post-upgrade commands don't work when we depend on private
          # modules since we haven't figured out how to get the necessary SSH
          # config into the renovate container. Dep updates that impact
          # generated code will fail CI and need to be updated manually.
          #
          # RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: '["^git submodule update --init$", "^make generate$", "^install-tool golang \\$\\(grep -oP \"\\^go \\\\K\\.\\+\" go\\.mod\\)$", "^make go.lint$"]'
        with:
          configurationFile: .github/renovate.json5
          token: '${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}'
